services:
  # === PostgreSQL for OrderService ===
  postgres-order:
    image: postgres:16
    container_name: postgres-order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb
    ports:
      - "5433:5432"   # host:container
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

  # === PostgreSQL for PortfolioService ===
  postgres-portfolio:
    image: postgres:16
    container_name: postgres-portfolio
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfoliodb
    ports:
      - "5434:5432"   # host:container
    volumes:
      - postgres_portfolio_data:/var/lib/postgresql/data

  # === RabbitMQ ===
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # broker port
      - "15672:15672" # management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # === OrderService ===
  order-service:
    build: ./OrderService
    container_name: order-service
    depends_on:
      - postgres-order
      - rabbitmq
    environment:
      ConnectionStrings__Default: "Host=postgres-order;Port=5432;Database=ordersdb;Username=postgres;Password=postgres"
      RabbitMQ__Host: "rabbitmq"
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "5001:80"   # http://localhost:5001

  # === PortfolioService ===
  portfolio-service:
    build: ./PortfolioService
    container_name: portfolio-service
    depends_on:
      - postgres-portfolio
      - rabbitmq
    environment:
      ConnectionStrings__Default: "Host=postgres-portfolio;Port=5432;Database=portfoliodb;Username=postgres;Password=postgres"
      RabbitMQ__Host: "rabbitmq"
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "5002:80"   # http://localhost:5002

  # === PriceService ===
  price-service:
    build: ./PriceService
    container_name: price-service
    depends_on:
      - rabbitmq
    environment:
      RabbitMQ__Host: "rabbitmq"
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "5003:80"   # http://localhost:5003 (optional, for logs/health)

volumes:
  postgres_order_data:
  postgres_portfolio_data:
  rabbitmq_data:
